name: workflow name

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build angular project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ angular-app-deploy.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ angular-app-deploy.AWS_SECRET_ACCESS_KEY }}
          application_name: Angular code deployment
          environment_name: Angularcodedeployment-env
          version_label: 12345
          region: us-west-2
          deployment_package: dist
